spring:
  application:
    name: xiaobai-ai-agent
  profiles:
    active: local
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    dashscope:
      chat:
        options:
          model: qwen-max


server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.htmlAdd commentMore actions
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaobai.aiagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn